### ISSUE TITLE
Feature 2. Cryptopunks as bosses?

### ISSUE THREAD

**Issue by iurii2002** [LedgerHQ/solidity-exercise#4]
I am a bit confused about connecting game bosses to cryptopunks by using interface. 
Cryptopunks is not an erc-721 token, there is not so much interesting data we can get from the contract. 
We may connect our boss to a punk with adding random number from 1 to 10000 and then using punk's API on frontend, but we do not really need an interface for it, do we?

**Comment by imqdee** [comment]
Cryptopunk is a bad example, will probably update the exercise to point to a 721-compliant contract, which will make more sense. Feel free to implement any other famous 721 collections.
The idea is to link the metadata of the NFT targetted to the boss on-chain, you don't need to create a frontend for this exercise, it is only focused on Solidity

**Comment by imqdee** [comment]
I'm closing @iuriizzz, feel free to reopen it if you need more details on the same topic or create a new one for everything else
